### DISCUSSION TITLE
Run command twice instead of up/down + stop

### DISCUSSION THREAD

**Discussion by Pulpyyyy** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#25] [Ideas]
Hi,

Could the component be extended to allow sending a command "twice" instead of "up/down + stop"

I do have a dual relay to manage some of my  shutters :
- R1 signal => shutter goes up
- R1 signal again => shutter stops

- R2 signal => shutter goes down
- R2 signal again => shutter stops

It is mandatory to send a second signal to stop the motor, otherwise it overloads
Mixing R1/R2 signals should be avoid.

Regards

**Comment by nagyrobi** [comment]
That's why the scripts are used. Look at the [examples](https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based#switched-covers).

To open (go up) and close (go down) it's pretty straightforward.
To stop you'd have to include a template to check if it's going up or down and select R1 or R2 based on that.
`"{{ 'R1' if states('cover.yourcover') == 'opening' else 'R2' }}"`

**Reply by marcob79** [reply]
i need to do something similar. so trigger a switch if the cover is opening an another one if closing in order to succesully stop it. Anyway it seems that, as soon as home assistant call the 
`stop_script_entity_id: script.tenda_sala_stop`

the cover entity state changes immediatly, for example, to open, so I cannot check anymore inside the script is we were opening or closing.
Am I doing something wrong? is there a way to check opening / closing state while stop_script_entity_id is running?

thanks
bye
Marco

**Reply by Pulpyyyy** [reply]
Hello,

That's the behavior I have too. I'm not able to distinguish opening from closing at the stop.
I was thinking about setting up a last action sensor/variable to be able to use it in a condition in stop script.
That would be nice to have a build-in mechanism

**Comment by marcob79** [comment]
@nagyrobi do you think that it would be possible to modify the behaviour of this custom component in order to do not modify the status of the script immediately after the stop script is executed, but at the end of the stop script execution?

**Reply by nagyrobi** [reply]
You should adjust the scripts properly as @Pulpyyyy suggests, by employing a binary sensor which can be True if opening and False if closing. Of if you want to be even more sure, you can use two binary sensors, each for opening and closing, which are only True during movement, and you can set them to False from the script, after you finish with your relays.

And based on that you can program the logic.

**Comment by marcob79** [comment]
I don't think binary sensor is suitable in this case. What about if someone
press stop and the cover is already stopped?

Why the cover status is modified as soon as the stop script will be
executed?

Il ven 30 apr 2021, 22:21 nagyrobi ***@***.***> ha scritto:

**Reply by nagyrobi** [reply]
> Why the cover status is modified as soon as the stop script will be executed?

This is how Home Assistant works internally. Scripts have no return value, there's nowhere for Home Assistant to know if the script was executed or not. They are shot away and that's it. It's like this by design of HA.
This component was already modified in a way to be as flexible as possible by calling these scripts for the commands, the rest of the implementation has to be through these. If you don't think you can do it like that, be my guest to fork and modify the component for yourself - that's the best part of open source.

**Comment by nagyrobi** [comment]
Or maybe you should check the original version:
https://github.com/davidramosweb/home-assistant-custom-components-cover-time-based

**Comment by Pulpyyyy** [comment]
Here is what i've done
```
input_text:
  covertest_last:
    initial: ""

cover:
  covertest:
    name: "covertest"
    travelling_time_up: 18
    travelling_time_down: 15
    close_script_entity_id: script.close_covertest
    stop_script_entity_id: script.stop_covertest
    open_script_entity_id: script.open_covertest
    send_stop_at_ends: True

script:
  open_covertest:
    alias: Open covertest
    sequence:
    - service: cover.open_cover
      data:
      entity_id: cover.volet_sdbh
    - service: input_text.set_value
      target:
      entity_id: input_text.covertest_last
      data:
      value: open
  close_covertest:
    alias: Close covertest
    sequence:
    - service: cover.close_cover
      data:
      entity_id: cover.volet_sdbh
    - service: input_text.set_value
      target:
      entity_id: input_text.covertest_last
      data:
      value: close
  stop_covertest:
    alias: Stop covertest
    sequence:
    - service: "{% if is_state('input_text.covertest_last', 'open') %}
        script.open_covertest
      {% elif is_state('input_text.covertest_last', 'close') %}
        script.close_covertest
      {% endif %}"
    - service: input_text.set_value
      target:
      entity_id: input_text.covertest_last
      data:
      value: "{% if is_state('input_text.covertest_last', 'open') %}
        stop_open
      {% elif is_state('input_text.covertest_last', 'close') %}
        stop_close
      {% endif %}"
```


[covertest.yaml.txt](https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based/files/6409906/covertest.yaml.txt)


![cover](https://user-images.githubusercontent.com/32004297/116788108-18121d00-aaa8-11eb-97e1-ec945d90a73b.gif)
