### DISCUSSION TITLE
Feature Request + Questions

### DISCUSSION THREAD

**Discussion by Stupco** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#32] [Ideas]
I was struggling to find a way to make this work using counters, but found this awesome component. So firstly, THANKS!

I have a few things:

#Feature Request
1. Is there a way to either pass data through in the script call OR can we just call the remote service? It would save having to write a script for EVERY cover (I have a lot). Example:
```
      close_script_entity_id: >
        service: remote.send_command
        data:
          entity_id: remote.rmpro_remote
          command: b64:sgD0AqIzDBk
```
#Questions
2.  I have blinds where I can set them in privacy mode when they are at 50% position. I have a separate RF signal for this, but obviously this unique use case means I can just set them at 50% value manually. It just means that I won't have the "opening" or "closing" states that I would prefer.

3. I also have grouped blinds with a separate RF command so I can control a whole room, but creating a separate entity means their individual positions won't update.

Fully aware that question 2 and 3 are very specific to my use case, just curious if you might have some knowledge you could drop on me.

Again, amazing work as always nagyrobi!

I might be better doing my own counter and automations to address my specific needs, [I'm just stumped though.](https://community.home-assistant.io/t/cover-template-position-template-timer/305676/5)

**Comment by nagyrobi** [comment]
No.
Use the cover_set_position service.
Use cover groups, or specify multiple covers separated by comma, instead of the common Rf codes.

**Reply by steelincable** [reply]
I just ran into scenario 3 mentioned by @Stupco above and upon going through the readme have the functionality implemented and wanted to share.  I have a bay window with 3 separate RF rollerblinds.  Each are on their own channel and all three are on a group channel as well.  I have all 4 entities shown in lovelace.  My goal is to correctly show the position of each individual roller blind when I use the group channel.  It was pretty easy and all I had to do was use the set_known_action in my sunrise and sunset automations.

```
  - service: cover.open_cover
    target:
      entity_id: cover.bay_window_all_rollerblinds
  - service: cover_rf_time_based.set_known_action
    data:
      entity_id: cover.bay_window_1_rollerblinds
      action: open
  - service: cover_rf_time_based.set_known_action
    data:
      entity_id: cover.bay_window_2_rollerblinds
      action: open
  - service: cover_rf_time_based.set_known_action
    data:
      entity_id: cover.bay_window_3_rollerblinds
      action: open
```

I hope this helps!  Also a big THANK YOU to @nagyrobi for all your work on this project!

**Reply by Stupco** [reply]
@nagyrobi how about allowing us to pass a variable to the script so that we can not action the actual RF command but still allow counter for individual blinds.

Suggesting something like:
```
cover:
- platform: cover_rf_time_based
  devices:
    b3_0:
      name: "Bedroom 3: all blinds"
      travelling_time_up: 94
      travelling_time_down: 94
      close_script_entity_id: script.b3_0_down
        data:
          type: "group"
      stop_script_entity_id: script.b3_0_stop
        data:
          type: "group"
      open_script_entity_id: script.b3_0_up
        data:
          type: "group"
    b3_1:
      name: "Bedroom 3: blind 1"
      travelling_time_up: 56
      travelling_time_down: 56
      close_script_entity_id: script.b3_1_down
      stop_script_entity_id: script.b3_1_stop
      open_script_entity_id: script.b3_1_up
    b3_2:
      name: "Bedroom 3: blind 2"
      travelling_time_up: 94
      travelling_time_down: 94
      close_script_entity_id: script.b3_2_down
      stop_script_entity_id: script.b3_2_stop
      open_script_entity_id: script.b3_2_up

#Scripts:
b3_0_down:
  alias: Close blind
  sequence:
    - service: remote.send_command
      data:
        entity_id: remote.rmpro_remote
        command: b64:sgD0A
    - service: cover.close_cover
      data:
        entity_id: cover.b3_1
    - service: cover.close_cover
      data:
        entity_id: cover.b3_2

b3_1_down:
  alias: Close blind
  sequence:
    - service: >
        {% if {{type}}, "group") %}
          script.dummy
        {% else %}
          remote.send_command
        {% endif %}
        data:
          entity_id: remote.rmpro_remote
          command: by64:sgD8AJ8D

#Automations:
- id: b3_0
  alias: Updates Bedroom 3 blinds
  trigger:
    - platform: state
      entity_id: cover.b3_1
      attribute: current_position
    - platform: state
      entity_id: cover.b3_2
      attribute: current_position
  action:
    - service: python_script.set_state
      data_template:
        entity_id: cover.b3_0
        current_position:
          '{{ (((state_attr("cover.b3_1", "current_position") | int)
          + (state_attr("cover.b3_2", "current_position") | int)) / 2) | int}}'
  mode: parallel
```
