### ISSUE TITLE
Call stop script when cover is opened

### ISSUE THREAD

**Issue by fabiobott** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#2]
In lovelace I click on up button and this integration call up script.
When cover is opened I would the integration call stop script
Is it possible?
Thanks

**Comment by Torrentus** [comment]
Can't you just call your stop script at the end of your open script (if needed with time delay in it?)

**Comment by fabiobott** [comment]
It's not equal
if total time is 30 seconds and I click on up button and later 10 seconds I click down and again up, the first script will call stop and it's not correct.
I should cancel the first script if the user clicks another button

**Comment by VDRainer** [comment]
I also think the stop script should be called if the cover is fully openend or closed.
I'm trying to use it with relays that turn the cover up an down and they stay active if the cover reached the end positions.
BTW: Great that there's a custom component for this. :+1: 
Implementing this with scripts and automations is a real pain.

**Comment by nagyrobi** [comment]
This is on-purpose not like that, because that would prevent sending out the trigger again if needed. Sometimes it may happen that due to RF interference the signal is not received by the cover, and since there’s no feedback from the cover itself, HA will assume the cover changed state while this might not be true. In such cases the user wishes to send out the trigger again, this was followed by a stop until now.

If you're using relays, try using the original component: https://github.com/davidramosweb/home-assistant-custom-components-cover-time-based

**Comment by nagyrobi** [comment]
I've created an extra feature for this. Update the component to the latest, and add `send_stop_at_ends: True` to your cover config.

**Comment by fabiobott** [comment]
Great!
Thank you very much.
This component is fantastic

**Comment by VDRainer** [comment]
Thanks a lot!

**Comment by nagyrobi** [comment]
Could you share a sample of your scripts for me to learn how you work with relays?

**Comment by VDRainer** [comment]
Sure.
There are two relays for each cover.
One for power, the other for up/down.
The relays are activated over mqtt topics.
```yaml
### Cover
#################################################################
cover:
  - platform: cover_rf_time_based
    devices:
      my_test_cover_time_based:
        name: My Test Cover CC
        travelling_time_up: 26
        travelling_time_down: 24
        send_stop_at_ends: True
        close_script_entity_id: script.cover_test_cc_close
        stop_script_entity_id: script.cover_test_cc_stop
        open_script_entity_id: script.cover_test_cc_open


### Scripts
#################################################################
script:
  cover_test_cc_open:
    sequence:
      - service: mqtt.publish
        data:
          topic: 'home/mcp23017_2/mm1_a1_out' # open/close
          payload: 'ON'
      - service: mqtt.publish
        data:
          topic: 'home/mcp23017_2/mm1_a0_out' # power
          payload: 'ON'

  cover_test_cc_close:
    sequence:
      - service: mqtt.publish
        data:
          topic: 'home/mcp23017_2/mm1_a1_out' # open/close
          payload: 'OFF'
      - service: mqtt.publish
        data:
          topic: 'home/mcp23017_2/mm1_a0_out' # power
          payload: 'ON'

  cover_test_cc_stop:
    sequence:
      - service: mqtt.publish
        data:
          topic: 'home/mcp23017_2/mm1_a0_out' # power
          payload: 'OFF'
      - service: mqtt.publish
        data:
          topic: 'home/mcp23017_2/mm1_a1_out' # open/close
          payload: 'OFF'
```
