### ISSUE TITLE
Adding cover to configuration.yaml cause KNX stop working

### ISSUE THREAD

**Issue by sepa85** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#28]
Hi guys, I'm noticing some problem with this integration. I've installed it with HACS (version 1.0.8), and I'm using HASSIO on raspberry 3 (core version 2021.5.1, supervisor 2021.04.3, OS 5.13).

I've installed the custom component, rebooted, added script and configuration, rebooted.

My config is:

```
cover:
- platform: cover_rf_time_based
  devices:
    veneziane_soggiorno_dx_knx:
      name: "Veneziane soggiorno dx knx"
      travelling_time_up: 43
      travelling_time_down: 43
      close_script_entity_id: script.veneziane_soggiorno_dx_discesa
      stop_script_entity_id: script.veneziane_soggiorno_dx_stop
      open_script_entity_id: script.veneziane_soggiorno_dx_salita
      send_stop_at_ends: False #optional
      aliases: #optional
        - veneziane_soggiorno_dx_knx
```

As I reboot, KNX is not working anymore. Different error is given, but seem to be kindly random.

The most common is: 

> Setup failed for knx: Unable to import component: No module named 'xknx.dpt'

Do you have some ideas where I can start from? Thank you.
