### ISSUE TITLE
Feature Request + Questions

### ISSUE THREAD

**Issue by Stupco** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#31]
I was struggling to find a way to make this work using counters, but found this awesome component. So firstly, THANKS!

I have a few things:

#Feature Request
1. Is there a way to either pass data through in the script call OR can we just call the remote service? It would save having to write a script for EVERY cover (I have a lot). Example:
```
      close_script_entity_id: >
        service: remote.send_command
        data:
          entity_id: remote.rmpro_remote
          command: b64:sgD0AqIzDBk
```
#Questions
2.  I have blinds where I can set them in privacy mode when they are at 50% position. I have a separate RF signal for this, but obviously this unique use case means I can just set them at 50% value manually. It just means that I won't have the "opening" or "closing" states that I would prefer.

3. I also have grouped blinds with a separate RF command so I can control a whole room, but creating a separate entity means their individual positions won't update.

Fully aware that question 2 and 3 are very specific to my use case, just curious if you might have some knowledge you could drop on me.

Again, amazing work as always nagyrobi!

I might be better doing my own counter and automations to address my specific needs, [I'm just stumped though.](https://community.home-assistant.io/t/cover-template-position-template-timer/305676/5)
