### ISSUE TITLE
Config device key is ignored

### ISSUE THREAD

**Issue by VDRainer** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#5]
The cover gets the entity_id from the friendly name, not from the devices key.
```
cover:
  - platform: cover_rf_time_based
    devices:
      my_test_cover_time_based: # this should be the entity_id
        name: Test CC # the name is used for the entity_id
        travelling_time_up: 26
        travelling_time_down: 24
        send_stop_at_ends: True
        close_script_entity_id: script.cover_test_cc_close
        stop_script_entity_id: script.cover_test_cc_stop
        open_script_entity_id: script.cover_test_cc_open
```
![Auswahl_356](https://user-images.githubusercontent.com/26381449/84449088-aab98b80-ac4c-11ea-9dfb-e42c56457263.png)
