### ISSUE TITLE
Using cover_rf_time_based.set_known_position-servicewhile the curtain is moving the curtain fails to stop a the target location

### ISSUE THREAD

**Issue by nl0pvm** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#55]
I set the known_position to compensate for the delay (app 1-2 secs) in sending the commands. I use the following code in the script. However the stop_script_entity_id-script is never called after using the cover_rf_time_based.set_known_position-service
```
      - service: cover_rf_time_based.set_known_position
        data:
          confident: false
          entity_id: cover.office
          position: "{{ starting_position_calculated }}"
          position_type: current
```
